application: llsnippets
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/snippets@.*llsnippets\.appspotmail\.com 
  script: receive_email.py
  login: admin

- url: .*
  script: main.py
  secure: always
    
inbound_services:
- mail
